import React from 'react';
import { motion } from 'framer-motion';
import { BookOpen, Video, Users, Clock, Zap, Target, Sparkles } from 'lucide-react';

export const Features = () => {
  const features = [
    {
      icon: <BookOpen className="w-5 h-5" />,
      title: "Extensive QBank",
      description: "Over 5,000 MCQ questions tailored to the latest AMC CAT blueprint with detailed Australian guideline references.",
      color: "var(--color-brand-violet)"
    },
    {
      icon: <Video className="w-5 h-5" />,
      title: "High-Yield Lectures",
      description: "Comprehensive visual library covering complex Internal Medicine, Surgery, and Pediatrics.",
      color: "var(--color-brand-blue)"
    },
    {
      icon: <Users className="w-5 h-5" />,
      title: "Clinical Roleplays",
      description: "Interactive scenarios with peers or AI-powered patients to master communication and clinical skills.",
      color: "var(--color-brand-gold)"
    },
    {
      icon: <Clock className="w-5 h-5" />,
      title: "Smart Study Planner",
      description: "Personalized study schedules generated by our algorithm based on your exam date and daily availability.",
      color: "var(--color-brand-violet)"
    },
    {
      icon: <Zap className="w-5 h-5" />,
      title: "Performance Analytics",
      description: "Real-time tracking to identify weak areas with precision, focusing your efforts where they matter most.",
      color: "var(--color-brand-blue)"
    },
    {
      icon: <Target className="w-5 h-5" />,
      title: "Mock Exams",
      description: "Full-length simulations that replicate the actual test environment, timing, and pressure.",
      color: "var(--color-brand-gold)"
    }
  ];

  return (
    <section className="bg-white py-24 sm:py-32 relative">
      <div className="max-w-7xl mx-auto px-6 lg:px-8">
        
        {/* Simplified Header */}
        <div className="max-w-3xl mb-24">
          <motion.div 
            initial={{ opacity: 0, x: -20 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            className="flex items-center gap-3 text-brand-gold mb-6"
          >
            <Sparkles className="w-5 h-5" />
            <span className="text-xs font-black uppercase tracking-[0.3em]">Platform Excellence</span>
          </motion.div>
          <h2 className="text-5xl md:text-6xl font-black text-brand-dark tracking-tighter leading-[0.95]">
            Engineered for <br />
            <span className="text-gradient-brand">Clinical Mastery.</span>
          </h2>
        </div>

        {/* Feature Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-x-12 gap-y-16">
          {features.map((feature, idx) => (
            <motion.div
              key={idx}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: idx * 0.1 }}
              className="group flex flex-col"
            >
              {/* Icon & Title Header - Locked Together */}
              <div className="flex items-center gap-4 mb-5">
                <div 
                  className="shrink-0 w-12 h-12 rounded-xl flex items-center justify-center bg-slate-50 transition-all duration-500 group-hover:scale-110"
                  style={{ color: feature.color }}
                >
                  {feature.icon}
                </div>
                
                {/* Connecting Line */}
                <div className="h-px bg-slate-100 flex-grow relative overflow-hidden">
                    <motion.div 
                        initial={{ x: "-100%" }}
                        whileInView={{ x: "0%" }}
                        transition={{ duration: 1, delay: idx * 0.2 }}
                        className="absolute inset-0 bg-gradient-to-r from-transparent via-slate-300 to-transparent"
                    />
                </div>
              </div>

              {/* Data Block */}
              <div className="pl-1">
                <h3 className="text-xl font-black text-brand-dark tracking-tight mb-3">
                  {feature.title}
                </h3>
                <p className="text-slate-500 text-[15px] leading-relaxed font-medium">
                  {feature.description}
                </p>
                
                {/* Vertical Accent Bar (Connects Icon column visually to the text) */}
                <div 
                    className="mt-6 h-1 w-12 rounded-full opacity-20 transition-all duration-500 group-hover:w-full group-hover:opacity-40"
                    style={{ backgroundColor: feature.color }}
                />
              </div>
            </motion.div>
          ))}
        </div>
        
        {/* Subtle Bottom Accent */}
        <div className="mt-32 pt-8 border-t border-slate-50 flex justify-between items-center text-slate-300">
            <span className="text-[10px] font-black uppercase tracking-[0.4em]">Integrated Suite</span>
            <div className="flex gap-2">
                <div className="w-1.5 h-1.5 rounded-full bg-brand-violet/20" />
                <div className="w-1.5 h-1.5 rounded-full bg-brand-blue/20" />
                <div className="w-1.5 h-1.5 rounded-full bg-brand-gold/20" />
            </div>
        </div>
      </div>
    </section>
  );
};