/**
 * Terms and Conditions / Privacy Policy content.
 *
 * Converted from the source .docx files supplied by AMC Catalyst. Kept as data
 * in the bundle rather than fetched at runtime so the pages work in the
 * deployed single-file build with no extra request and no server dependency.
 *
 * To amend: edit here. The .docx originals are not read by the app.
 */

// Fixed, not computed. A legal document states the date it took effect — if
// this were `new Date()` the deployed site would silently claim the policy was
// updated today, every day, and no user could tell which version they agreed to.
// Change it deliberately when the text changes.
export const LEGAL_EFFECTIVE_DATE = '23 August 2026';
export const LEGAL_LAST_UPDATED = '23 August 2026';

export const TERMS = {
  title: "Terms and Conditions",
  version: "1.0",
  blocks: [
    { t: "h2", x: "Introduction and Acceptance of Terms" },
    { t: "p", x: "These Terms and Conditions (\"Terms\") constitute a legally binding agreement between you (\"You\", \"Your\", \"User\") and AMC Catalyst [Legal Entity Name] (\"AMC Catalyst\", \"we\", \"our\", \"us\"), governing your access to and use of the website, and related services offered by AMC Catalyst, including study notes, mock examinations, multiple-choice question (\"MCQ\") banks, exam recalls, and other learning resources for candidates preparing for the Australian Medical Council (AMC) examinations and other medical licensing, entrance, or competitive examinations (collectively, the \"Platform\" and \"Services\")." },
    { t: "p", x: "By creating an account, accessing, browsing, or using the Platform in any manner, you acknowledge that you have read, understood, and agree to be bound by these Terms, along with our Privacy Policy, which is incorporated herein by reference. If you do not agree with any part of these Terms, you must not access or use the Platform." },
    { t: "p", x: "We reserve the right to modify, amend, or update these Terms at any time, in our sole discretion. Any changes will be effective upon posting the revised Terms on the Platform, and where required under Applicable Law, we will notify you through your registered email address. Your continued use of the Platform following any such change constitutes your acceptance of the revised Terms. We encourage you to review these Terms periodically." },
    { t: "h2", x: "Eligibility" },
    { t: "clause", x: "By using the Platform, you represent and warrant that you are at least eighteen (18) years of age and possess the legal capacity to enter into a binding contract under Applicable Law. Where a user is below eighteen (18) years of age, use of the Platform shall be undertaken only with the involvement, supervision, and consent of a parent or lawful guardian." },
    { t: "clause", x: "You represent and warrant that all information you provide to us in connection with your registration and use of the Platform, including your academic and professional details, is true, accurate, current, and complete." },
    { t: "clause", x: "We reserve the right to refuse registration to, or terminate the account of, any person who we reasonably believe does not meet these eligibility criteria or has provided false or misleading information." },
    { t: "h2", x: "Account Registration and One Account, One User Policy" },
    { t: "clause", x: "To access most of the Services, you are required to register for an account by providing your name, email address, mobile number, country, year of graduation, and other requested details, and by creating a password." },
    { t: "clause", x: "You are solely responsible for maintaining the confidentiality of your login credentials and for all activities that occur under your account. You agree to notify us immediately at [to be provided] of any unauthorised use of your account or any other breach of security." },
    { t: "clause", x: "Each account is strictly personal to the individual who registers it and is licensed for use by that individual only. You shall not share, lend, rent, sell, transfer, or otherwise permit any other person to access or use your account or login credentials, whether for consideration or otherwise, and shall not use more than one account for yourself." },
    { t: "clause", x: "We actively monitor account activity, including login timestamps, IP addresses, device identifiers, device fingerprints, approximate location, and the pattern and number of concurrent or simultaneous sessions, to detect and prevent unauthorised account sharing." },
    { t: "clause", x: "Where we reasonably determine, in our sole discretion, that an account is being shared, accessed simultaneously from an unusual number of devices or locations, or otherwise used in violation of this Section, we may, without prior notice, suspend or permanently terminate the account, restrict access to the Services, and take any other action available to us under these Terms or Applicable Law. No refund shall be payable in such circumstances, and Section 6 (No Refund Policy) shall apply." },
    { t: "h2", x: "Subscription, Fees and Payment" },
    { t: "clause", x: "Access to certain notes, mock tests, MCQ banks, recalls, and other premium content requires payment of applicable subscription fees, as displayed on the Platform at the time of purchase. All fees are quoted in the currency displayed on the Platform and are exclusive of applicable taxes, unless stated otherwise." },
    { t: "clause", x: "Payments made through the Platform are processed by authorised third-party payment gateway providers. By making a payment, you agree to be bound by the terms and privacy policy of the applicable payment gateway provider, in addition to these Terms." },
    { t: "clause", x: "Subscriptions may be offered on a one-time, time-bound, or recurring/auto-renewing basis, as specified at the time of purchase. Where a subscription is auto-renewing, it will automatically renew at the end of each billing cycle unless you cancel it prior to the renewal date in accordance with the cancellation process specified on the Platform." },
    { t: "clause", x: "We reserve the right to change our subscription fees and plans at any time. Any change in fees will apply prospectively and will not affect a subscription that you have already paid for, except as otherwise permitted under Applicable Law." },
    { t: "clause", x: "You agree to provide accurate and complete billing and bank/payment information, including for the purposes of identity verification, fraud prevention, and processing any refund we may be legally required to make." },
    { t: "h2", x: "No Refund Policy" },
    { t: "clause", x: "ALL PAYMENTS MADE TOWARDS SUBSCRIPTIONS, COURSES, NOTES, MOCK TESTS, MCQ BANKS, RECALLS, OR ANY OTHER SERVICE OR CONTENT ON THE PLATFORM ARE FINAL AND NON-REFUNDABLE, WHETHER IN PART OR IN FULL, ONCE PAYMENT HAS BEEN SUCCESSFULLY PROCESSED, REGARDLESS OF WHETHER YOU HAVE ACCESSED OR UTILISED THE CONTENT." },
    { t: "clause", x: "This No Refund Policy applies irrespective of the reason for the refund request, including but not limited to change of mind, dissatisfaction with content, failure to clear an examination, inability to complete a course within its validity period, or suspension/termination of your account for breach of these Terms (including the One Account, One User policy in Section 3 or the Content Protection restrictions in Section 7)." },
    { t: "clause", x: "Notwithstanding the foregoing, we may, at our sole discretion or where mandated under Applicable Law, process a refund or payment reversal in cases of duplicate charges, verified payment gateway or technical errors resulting in erroneous charges, or as otherwise required by a competent court, regulator, or Applicable Law." },
    { t: "clause", x: "You acknowledge and agree that you have had the opportunity to review sample content, course structure, and pricing information prior to making a purchase, and that your purchase decision is made with full knowledge of this No Refund Policy." },
    { t: "h2", x: "Content Protection: Restrictions on Screenshots, Downloading and Copying" },
    { t: "clause", x: "All notes, mock tests, MCQs, recalls, and other study material made available on the Platform (\"Content\") are the proprietary and confidential intellectual property of AMC Catalyst or its licensors, and are protected under applicable copyright, trademark, and other intellectual property laws." },
    { t: "clause", x: "You are strictly prohibited from: (i) taking screenshots, screen recordings, or photographs of any Content; (ii) downloading, saving, copying, printing, or exporting any Content in any format; (iii) using screen-capture, screen-mirroring, automation, scraping, or similar third-party tools or browser extensions to extract Content; (iv) reproducing, distributing, publishing, transmitting, displaying, selling, licensing, or creating derivative works from any Content; and (v) sharing, uploading, or redistributing any Content on any other website, application, messaging platform, or physical medium, whether for commercial gain or otherwise." },
    { t: "clause", x: "To enforce this Section, the Platform may employ technical protection measures, including but not limited to disabling right-click, copy, and print functions, watermarking Content with your account details, restricting or detecting screenshot and screen-recording functionality where technically feasible, limiting access to streaming/view-only formats, and monitoring access and usage patterns for signs of unauthorised copying." },
    { t: "clause", x: "Any actual or attempted violation of this Section shall constitute a material breach of these Terms and may result in immediate suspension or termination of your account without any refund, in addition to any civil or criminal liability, injunctive relief, and damages that we may pursue against you under Applicable Law for infringement of our intellectual property rights and breach of confidentiality." },
    { t: "clause", x: "You acknowledge that unauthorised reproduction or distribution of the Content causes irreparable harm to AMC Catalyst for which monetary damages may be an inadequate remedy, and you agree that we shall be entitled to seek injunctive or other equitable relief in addition to any other remedies available at law." },
    { t: "h2", x: "Accuracy of Content and Educational Disclaimer" },
    { t: "clause", x: "The notes, mock tests, MCQs, and recalls made available on the Platform are prepared based on inputs from past candidates, subject matter experts, and publicly available examination patterns, and are intended solely as supplementary study aids." },
    { t: "clause", x: "Recalls are based on the recollection of past examination candidates and are provided on an \"as-is\" basis. We do not guarantee that recalled questions are verbatim reproductions of actual examination questions, and we make no representation regarding their completeness, accuracy, or continued relevance to future examinations." },
    { t: "clause", x: "AMC Catalyst is an independent educational platform and is not affiliated with, endorsed by, or connected to the Australian Medical Council or any other examination body, unless expressly stated otherwise. Any references to \"AMC\" or other examination bodies are used solely to describe the subject matter of our Services." },
    { t: "clause", x: "We do not guarantee or warrant that use of the Platform or Content will result in your passing any examination, and we shall not be liable for any examination outcome, including failure to clear an examination." },
    { t: "h2", x: "User Conduct and Prohibited Uses" },
    { t: "p", x: "In addition to the restrictions set out in Section 6, you agree that you shall not:" },
    { t: "clause", x: "use the Platform for any unlawful purpose or in violation of any Applicable Law;" },
    { t: "clause", x: "impersonate any person or entity, or misrepresent your affiliation with any person or entity;" },
    { t: "clause", x: "upload or transmit any viruses, malware, or other harmful code;" },
    { t: "clause", x: "attempt to gain unauthorised access to the Platform, other users' accounts, or our systems and networks;" },
    { t: "clause", x: "use any automated means, including bots, crawlers, or scrapers, to access or extract data or Content from the Platform;" },
    { t: "clause", x: "engage in any activity that interferes with or disrupts the Platform or the servers/networks used to make it available;" },
    { t: "clause", x: "harass, abuse, or harm another user, or post any defamatory, obscene, or unlawful content on any interactive feature of the Platform (if applicable);" },
    { t: "clause", x: "resell, sublicense, or commercially exploit the Platform or any Content without our express prior written consent." },
    { t: "h2", x: "Intellectual Property Rights" },
    { t: "clause", x: "The Platform, including its design, layout, software, trademarks, logos, and all Content, is owned by or licensed to AMC Catalyst and is protected under applicable intellectual property laws. Subject to your compliance with these Terms and payment of applicable fees, we grant you a limited, non-exclusive, non-transferable, revocable, personal licence to access and view the Content solely for your own individual, non-commercial exam-preparation use." },
    { t: "clause", x: "Nothing in these Terms shall be construed as transferring any ownership rights in the Platform or Content to you. All rights not expressly granted to you under these Terms are reserved by AMC Catalyst." },
    { t: "clause", x: "If you submit any feedback, suggestions, or ideas regarding the Platform, you grant us a perpetual, irrevocable, royalty-free, worldwide licence to use such feedback for any purpose without any obligation to compensate you." },
    { t: "h2", x: "Third-Party Services and Links" },
    { t: "p", x: "The Platform may contain links to, or integrate with, third-party websites, applications, or services, including payment gateways. We do not control and are not responsible for the content, accuracy, or practices of such third-party services. Your use of any third-party service is governed by the terms and privacy policy of that third party, and we encourage you to review the same before use." },
    { t: "h2", x: "Suspension and Termination" },
    { t: "clause", x: "We may suspend or terminate your account and access to the Platform, with or without prior notice, if we reasonably believe that you have violated these Terms, including the One Account, One User policy (Section 3) or the Content Protection restrictions (Section 6), engaged in fraudulent or unlawful activity, or provided false information at the time of registration." },
    { t: "clause", x: "You may terminate your account at any time by contacting us at [to be provided] Termination of your account, whether by you or by us, shall not entitle you to any refund of fees already paid, and Section 5 (No Refund Policy) shall survive such termination." },
    { t: "clause", x: "Upon termination, your right to access the Platform and Content shall immediately cease, and we may delete your account data in accordance with our Privacy Policy, subject to any legal retention obligations." },
    { t: "h2", x: "Disclaimer of Warranties" },
    { t: "p", x: "THE PLATFORM AND ALL CONTENT ARE PROVIDED ON AN \"AS IS\" AND \"AS AVAILABLE\" BASIS, WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, OR NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE PLATFORM WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE, OR THAT THE PLATFORM OR OUR SERVERS ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS." },
    { t: "h2", x: "Limitation of Liability" },
    { t: "p", x: "TO THE MAXIMUM EXTENT PERMITTED UNDER APPLICABLE LAW, AMC CATALYST SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES, INCLUDING LOSS OF DATA, LOSS OF STUDY PROGRESS, LOSS OF INCOME OR PROFIT, OR EXAMINATION OUTCOMES, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE PLATFORM, WHETHER BASED ON CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. OUR AGGREGATE LIABILITY ARISING OUT OF OR RELATING TO THESE TERMS OR THE PLATFORM SHALL NOT EXCEED THE TOTAL SUBSCRIPTION FEES PAID BY YOU TO US IN THE SIX (6) MONTHS PRECEDING THE EVENT GIVING RISE TO THE CLAIM." },
    { t: "h2", x: "Indemnification" },
    { t: "p", x: "You agree to indemnify, defend, and hold harmless AMC Catalyst, its officers, directors, employees, and agents from and against any claims, liabilities, damages, losses, and expenses, including reasonable attorneys' fees, arising out of or in any way connected with your breach of these Terms, your violation of the Content Protection restrictions in Section 6, your violation of any Applicable Law, or your infringement of any third-party rights." },
    { t: "h2", x: "Privacy" },
    { t: "p", x: "Your use of the Platform is also governed by our Privacy Policy, which describes how we collect, use, store, and protect your Personal Information, including in connection with the One Account, One User policy and Content Protection measures described in these Terms. Our Privacy Policy is incorporated into these Terms by reference." },
    { t: "h2", x: "Governing Law and Dispute Resolution" },
    { t: "clause", x: "These Terms shall be governed by and construed in accordance with the laws of India, without regard to its conflict of law principles." },
    { t: "clause", x: "Any dispute, controversy, or claim arising out of or relating to these Terms, or the breach, termination, or invalidity thereof, shall first be attempted to be resolved through good-faith negotiation between the parties." },
    { t: "clause", x: "If such dispute is not resolved through negotiation within thirty (30) days, it shall be subject to the exclusive jurisdiction of the courts at kochi, India, and the parties hereby submit to such jurisdiction." },
    { t: "h2", x: "Grievance Officer" },
    { t: "p", x: "In accordance with Applicable Law, the contact details of our Grievance Officer are provided below:" },
    { t: "p", x: "Name: [to be provided]" },
    { t: "p", x: "Designation: Grievance Officer" },
    { t: "p", x: "Email: [to be provided]" },
    { t: "p", x: "Customer Support: [to be provided]" },
    { t: "p", x: "We aim to acknowledge grievances within 48 hours and endeavour to resolve them within 15 business days, subject to the nature and complexity of the complaint." },
    { t: "h2", x: "Miscellaneous" },
    { t: "clause", x: "Entire Agreement - These Terms, together with our Privacy Policy, constitute the entire agreement between you and AMC Catalyst with respect to your use of the Platform, and supersede all prior agreements and understandings, whether written or oral." },
    { t: "clause", x: "Severability - If any provision of these Terms is found to be invalid or unenforceable by a court of competent jurisdiction, the remaining provisions shall continue in full force and effect." },
    { t: "clause", x: "Waiver - No failure or delay by us in exercising any right under these Terms shall operate as a waiver of that right." },
    { t: "clause", x: "Assignment - You may not assign or transfer your rights or obligations under these Terms without our prior written consent. We may assign these Terms, in whole or in part, at our discretion, including in connection with a merger, acquisition, or sale of assets." },
    { t: "clause", x: "Force Majeure - We shall not be liable for any failure or delay in performance resulting from causes beyond our reasonable control, including natural disasters, internet or telecommunications failures, or governmental action." },
    { t: "clause", x: "Survival - Sections 5 (No Refund Policy), 6 (Content Protection), 9 (Intellectual Property Rights), 12 (Disclaimer of Warranties), 13 (Limitation of Liability), 14 (Indemnification), and 16 (Governing Law and Dispute Resolution) shall survive the termination of these Terms and your account." },
  ],
};

export const PRIVACY = {
  title: "Privacy Policy",
  version: "1.0",
  blocks: [
    { t: "h2", x: "INTRODUCTION" },
    { t: "p", x: "This Privacy Policy (\"Policy\") sets out the privacy practices of AMC Catalyst (\"AMC Catalyst\", \"we\", \"our\", or \"us\"), an online educational technology platform offering study notes, mock examinations, multiple-choice question (\"MCQ\") banks, exam recalls, and related learning resources to candidates preparing for the Australian Medical Council (AMC) examinations and other medical licensing, entrance, or competitive examinations (\"Services\"), with regard to the collection, use, disclosure, storage, transfer, and protection of the Personal Information (defined hereunder) of visitors, registered users, and any person (\"You/you\" or \"Your/your\") accessing or using our website, mobile applications, and related services (\"Platform\")." },
    { t: "p", x: "We respect your privacy and are committed to protecting your Personal Information. This Privacy Policy explains how we collect, use, store, process, disclose, and protect your information when you access or use our Platform, and ensures that your Personal Information is handled in compliance with the Digital Personal Data Protection Act, 2023, and any other legislation/framework which may be applicable (\"Applicable Law\")." },
    { t: "p", x: "Our goal is to provide a safe, transparent, and reliable digital learning experience to candidates around the world preparing for medical licensing examinations." },
    { t: "p", x: "This Policy, along with the Terms of Use applicable to the Platform, governs Your use and access of our Platform and Our Services. It also explains Your rights in relation to Your Personal Information and the process to contact Us in case of any grievance." },
    { t: "p", x: "By providing your consent to this Policy and/or accepting the Terms of Use, You expressly agree to the collection, storage, use, and transfer of your Personal Information as set out in this Policy. If you do not agree with the terms of this Privacy Policy, please refrain from using and accessing this Platform." },
    { t: "p", x: "We reserve the right to review/update this Privacy Policy from time to time to keep it current. This Privacy Policy is subject to change at any time. Where we are required to notify you of any changes, we shall make reasonable efforts to send such notification through your registered email address or other contact details provided by you. However, non-receipt of such notification due to reasons beyond our reasonable control (including blocked communications, outdated contact details, technical issues, or network failures) shall not invalidate the effectiveness of the revised Privacy Policy. Please review this Policy periodically." },
    { t: "p", x: "For the purpose of this Policy, \"Personal Information\" means any information that can either itself identify you as an individual (\"Personally Identifying Information\") or that can be connected to you indirectly by linking it to Personally Identifying Information, as defined under the Digital Personal Data Protection Act, 2023 and/or any other applicable legislation." },
    { t: "h2", x: "Scope" },
    { t: "clause", x: "As a visitor, you may browse the Platform to learn more about our Services. You are not required to provide Personal Information as a visitor. However, when you visit the Platform, we may collect certain information in the form of cookies to improve security, analyse trends, and administer the Platform." },
    { t: "clause", x: "We collect your Personal Information when you register for an account, subscribe to any of our courses, question banks, mock tests or study material packages, participate in activities on the Platform, or otherwise contact us, including through our Website, mobile applications, customer support channels, WhatsApp, or email communication." },
    { t: "clause", x: "We will only collect and process your Personal Information, with your consent where required under the Digital Personal Data Protection Act, 2023, and where we have a lawful basis for doing so, including:" },
    { t: "li", x: "where you voluntarily provide Personal Information to access or use our Services;" },
    { t: "li", x: "where processing is necessary to perform a contract with you, including registering your account and processing your subscription;" },
    { t: "li", x: "for compliance with legal or regulatory obligations;" },
    { t: "li", x: "for responding to emergencies or preventing fraud; or" },
    { t: "li", x: "for any other purpose permitted by Applicable Law." },
    { t: "clause", x: "Our primary goal in collecting your Personal Information is to verify your identity as a genuine, single, registered user, provide you access to the study material, notes, mock tests, MCQs and recalls you have subscribed to, process your payments, and continually improve the quality and security of our Services." },
    { t: "clause", x: "We do not track your activity across third-party websites, nor do we engage in targeted advertising based on behavioural tracking, unless you have provided express consent for the same." },
    { t: "clause", x: "All collection, storage, usage, and transfer of your Personal Information as set out in this Policy is done only in accordance with Applicable Law." },
    { t: "h2", x: "Information We Collect" },
    { t: "p", x: "Depending on how you interact with the Platform, we may collect the following categories of Personal Information:" },
    { t: "h3", x: "Contact and Identity Information" },
    { t: "p", x: "When you register for an account or use our Platform, we collect:" },
    { t: "li", x: "Full Name" },
    { t: "li", x: "Email Address" },
    { t: "li", x: "Mobile Number" },
    { t: "li", x: "Country of Residence" },
    { t: "li", x: "Profile Photograph (optional)" },
    { t: "li", x: "Username and account password (stored in encrypted form)" },
    { t: "h3", x: "Academic and Professional Information" },
    { t: "p", x: "To help us provide relevant exam-preparation content and to verify your eligibility to use certain Services, we may collect:" },
    { t: "li", x: "Year of Graduation" },
    { t: "li", x: "Medical Degree / Qualification and Institution Name" },
    { t: "li", x: "Examination(s) you are preparing for (e.g., AMC MCQ/CAT, KAPS, or other licensing examinations)" },
    { t: "li", x: "Registration/enrolment identification numbers, where applicable" },
    { t: "h3", x: "Payment and Bank Information" },
    { t: "p", x: "To process your subscription and enable access to paid notes, mock tests, MCQ banks, and recalls, we may collect:" },
    { t: "li", x: "Bank Account Number and IFSC/SWIFT Code" },
    { t: "li", x: "UPI ID" },
    { t: "li", x: "Billing Name and Billing Address" },
    { t: "li", x: "Transaction ID, Payment Status, Payment Method, Order Amount, and Date & Time of Payment" },
    { t: "li", x: "Last four digits of debit/credit card, where applicable//Payments made through the Platform are processed by authorised third-party payment gateway providers. We do not store your complete debit card, credit card, UPI PIN, CVV, net banking credentials, or other sensitive financial authentication data on our servers. Bank account details that you provide are used solely for the purposes of processing your subscription payment, verifying payment, reconciling failed or duplicate transactions, and processing any payment reversal that we are legally required to make. All such information is encrypted and processed in accordance with applicable banking and data protection regulations." },
    { t: "h3", x: "Study Activity and Usage Information" },
    { t: "p", x: "To operate and improve the Services, we collect information relating to your use of our study material, including:" },
    { t: "li", x: "Notes, mock tests, and MCQ sets accessed or attempted" },
    { t: "li", x: "Test scores, attempt history, and progress tracking" },
    { t: "li", x: "Time spent on the Platform and specific content sections" },
    { t: "li", x: "Login timestamps, session duration, and device used to access the Platform" },
    { t: "li", x: "Number of concurrent or repeated logins and login locations" },
    { t: "h3", x: "Device and Technical Information" },
    { t: "li", x: "Device Type and Device Identifier" },
    { t: "li", x: "Operating System and Browser Type" },
    { t: "li", x: "IP Address" },
    { t: "li", x: "Crash Reports and Diagnostic Logs" },
    { t: "h3", x: "Customer Support Information" },
    { t: "li", x: "Your name and contact details" },
    { t: "li", x: "Communication history, support tickets, and feedback" },
    { t: "li", x: "Complaint details and other information you voluntarily share with us" },
    { t: "h3", x: "Location Information" },
    { t: "p", x: "With your permission, we may collect approximate location information to detect unauthorised or unusual account access, improve security, and personalise your experience. You may disable location permissions at any time through your device settings." },
    { t: "h2", x: "Collection of Personal Information" },
    { t: "clause", x: "Information You Provide - We collect Personal Information that you voluntarily provide while creating an account, subscribing to a course or question bank, making payment, contacting customer support, or otherwise communicating with us." },
    { t: "clause", x: "Information Collected Automatically - When you access the Platform, certain information is collected automatically through cookies and similar technologies, including your IP address, browser type, device information, operating system, pages visited, and study activity as described above." },
    { t: "clause", x: "Information Received from Third Parties - We may receive limited Personal Information from trusted third-party service providers, including payment gateway providers, analytics providers, and authentication service providers, only to the extent necessary to facilitate the Services requested by you or to comply with legal obligations." },
    { t: "h2", x: "Use of Your Personal Information" },
    { t: "clause", x: "We process your Personal Information only for lawful purposes and to the extent necessary to provide and improve the Services offered through the Platform." },
    { t: "clause", x: "To create and manage your account, authenticate your identity, enable secure login, and enforce our One Account, One User policy described in Section 7 below." },
    { t: "clause", x: "To grant you access to the notes, mock tests, MCQs, and recalls included in your subscription, and to track your usage and progress." },
    { t: "clause", x: "To process payments, verify transactions, generate invoices, prevent fraudulent or unauthorised transactions, and maintain financial records." },
    { t: "clause", x: "To communicate with you regarding OTPs, subscription confirmations, renewal reminders, service updates, security alerts, and other account-related notifications." },
    { t: "clause", x: "To detect, investigate, and prevent unauthorised account sharing, screenshotting, screen recording, downloading, scraping, or redistribution of our study material, and to enforce our Terms of Use and intellectual property rights." },
    { t: "clause", x: "To analyse usage trends, understand candidate preferences, and improve the accuracy, relevance, and quality of our notes, mock tests, MCQs, and recalls." },
    { t: "clause", x: "To detect and prevent fraud, misuse, or unauthorised access, and to comply with our legal, regulatory, and statutory obligations." },
    { t: "clause", x: "Where required under Applicable Law, we may send promotional communications, newsletters, or updates regarding our Services only with your consent, and you may opt out of such communications at any time." },
    { t: "h2", x: "One Account, One User Policy" },
    { t: "clause", x: "Each account registered on the Platform is strictly personal to the individual who created it and may be used by that individual only. Sharing of login credentials, simultaneous use of a single account by more than one person, or use of an account on behalf of another individual is strictly prohibited." },
    { t: "clause", x: "To enforce this policy and to protect the integrity of our Services, we monitor account activity, including login timestamps, IP addresses, device identifiers, device fingerprints, approximate location, and the number and pattern of concurrent sessions." },
    { t: "clause", x: "Where we reasonably suspect that an account is being shared, accessed from an unusual number of devices or locations, or otherwise used in violation of this policy, we may suspend or terminate the account without prior notice and without any obligation to issue a refund." },
    { t: "clause", x: "Personal Information collected for the purposes of this Section is used solely to verify account ownership, detect misuse, and enforce our Terms of Use, and is retained only for as long as necessary for these purposes, subject to Section 10 (Data Retention)." },
    { t: "h2", x: "Content Protection - Restrictions on Screenshots, Downloads and Copying" },
    { t: "clause", x: "All notes, mock tests, MCQs, recalls, and other study material made available on the Platform are proprietary and confidential content owned by or licensed to AMC Catalyst. You are not permitted to take screenshots, screen recordings, or photographs of; download, save, copy, print, scrape, or reproduce; or otherwise extract or redistribute any content available on the Platform, in whole or in part, through any means, including third-party screen-capture or automation tools." },
    { t: "clause", x: "To protect our content and enforce this restriction, the Platform may employ technical measures, including but not limited to disabling right-click and copy functions, watermarking content with your account details, restricting screenshot and screen-recording functionality where technically possible, and monitoring for unusual access or download patterns." },
    { t: "clause", x: "We may collect and process technical and usage information, including device identifiers, screenshot/screen-recording attempt logs (where technically detectable), IP addresses, and access patterns, solely for the purpose of detecting and preventing unauthorised copying or redistribution of our content and enforcing our intellectual property rights." },
    { t: "clause", x: "Any violation of this Section may result in immediate suspension or termination of your account without refund, in addition to any other legal remedies available to us, including action for breach of confidentiality and infringement of intellectual property rights." },
    { t: "h2", x: "Children's Privacy" },
    { t: "clause", x: "The Platform and the Services are intended for use by individuals who are legally capable of providing consent under Applicable Law and who are pursuing or have completed medical education. Where a user is below eighteen (18) years of age, access to or use of the Platform shall be undertaken only with the involvement, supervision, and consent of a parent or lawful guardian, to the extent required under Applicable Law." },
    { t: "clause", x: "We do not knowingly collect or process Personal Information from children in a manner prohibited by Applicable Law. If we become aware that Personal Information relating to a child has been collected without requisite consent, we shall take reasonable steps to suspend further processing and delete or anonymise such information, unless retention is required under Applicable Law." },
    { t: "h2", x: "Sharing and Disclosure of Personal Information" },
    { t: "clause", x: "We value your trust and do not sell, rent, or otherwise disclose your Personal Information to third parties for their independent marketing purposes. We share your Personal Information only to the extent necessary to provide the Services, comply with legal obligations, enforce our rights, or for other legitimate purposes set out in this Policy." },
    { t: "clause", x: "Where you make payments through the Platform, your payment-related information, including bank details, may be shared with authorised payment gateway providers, banks, and payment processing partners for the purposes of processing transactions, verifying payments, and preventing fraud. Such providers process your information in accordance with their own privacy policies and Applicable Law." },
    { t: "clause", x: "We may engage trusted third-party service providers to assist us in operating, hosting, securing, and improving the Platform, including cloud hosting, analytics, customer support, email delivery, and security monitoring providers. Such service providers are authorised to process Personal Information only on our behalf, subject to appropriate contractual confidentiality and security obligations." },
    { t: "clause", x: "We may disclose your Personal Information where required under Applicable Law, or where necessary to comply with a legal obligation, judicial order, or lawful request from a governmental authority, or to investigate suspected fraud, unauthorised account sharing, or unlawful redistribution of our content, or to protect our rights, property, and the integrity of the Platform." },
    { t: "clause", x: "In the event of a merger, acquisition, corporate restructuring, or sale of assets, your Personal Information may be transferred as part of such transaction, subject to the recipient entity implementing privacy safeguards substantially consistent with this Policy." },
    { t: "h2", x: "Data Retention" },
    { t: "p", x: "We retain your Personal Information only for as long as required to provide you the Services or to meet legal and regulatory obligations. Where processing is based on your consent, data will be retained only until such consent is withdrawn. Once no longer required, we will delete or anonymise the data, unless a longer retention period is mandated by Applicable Law, including for the purposes of maintaining financial and audit records, resolving disputes, and enforcing our No Refund Policy and One Account, One User policy." },
    { t: "h2", x: "Data Deletion" },
    { t: "p", x: "You may request deletion or modification of your data by contacting support at [to be provided]. Upon such request, we will delete/modify your data from our systems, unless retention is categorically required under Applicable Law. We may periodically review inactive or unused accounts and securely delete or anonymise Personal Information that is no longer required for the purposes for which it was collected. Deletion of your account may result in permanent loss of access to your subscription, study progress, test scores, and other account-related information, and shall not entitle you to any refund." },
    { t: "h2", x: "Security" },
    { t: "clause", x: "We undertake reasonable security safeguards to protect your Personal Information, including firewalls, data encryption, access authorization controls, and standard SSL certification to secure the connection between our servers and your device. Passwords are stored only in encrypted form." },
    { t: "clause", x: "We store and process your Personal Information on servers located in India, protected by physical as well as technological security measures, unless expressly stated otherwise." },
    { t: "clause", x: "In the event of a personal data breach, we will notify the Data Protection Board (constituted under the DPDP Act, 2023) within 72 hours, or at the earliest possible opportunity, of becoming aware of the breach, and take reasonable measures to contain and remediate the breach." },
    { t: "clause", x: "If you believe your account has been compromised, shared without authorisation, or misused, please contact us immediately at [to be provided]." },
    { t: "h2", x: "Cookies" },
    { t: "clause", x: "Our Platform uses cookies, which are small files stored on your device, to keep you signed in, remember your preferences, analyse traffic and usage, enhance security, and identify unauthorised or simultaneous logins in connection with our One Account, One User policy." },
    { t: "clause", x: "Non-essential cookies and tracking tools will be used only after you have given your explicit consent. Most browsers allow you to disable cookies; however, disabling cookies may affect your ability to access certain functionality on the Platform, including login and content-access features." },
    { t: "h2", x: "Third Party Services and AI Use" },
    { t: "clause", x: "We may engage trusted third-party service providers, including payment gateway providers, cloud hosting providers, analytics providers, and authentication providers, to operate and secure the Platform. These providers process your Personal Information only to the extent necessary to provide services on our behalf." },
    { t: "clause", x: "The Platform may use automated technologies, including AI-assisted tools, to generate, curate, or personalise study recommendations, practice question suggestions, and performance analytics based on your study activity. Such outputs are intended solely for exam-preparation and informational purposes and do not constitute a guarantee of examination results." },
    { t: "clause", x: "The Platform may contain links to third-party websites or resources that are not owned or controlled by us. We are not responsible for the privacy practices of such third-party websites, and we encourage you to review their privacy policies before providing any Personal Information to them." },
    { t: "h2", x: "Choice and Marketing Preferences" },
    { t: "p", x: "If you do not wish to receive marketing communications from us, you may unsubscribe using the link provided in our emails, update your communication preferences within your account settings, or contact us at [to be provided]-. Certain transactional and account-related communications, such as OTPs, payment confirmations, and security alerts, are necessary for the provision of the Services and may continue to be sent notwithstanding your decision to opt out of promotional communications." },
    { t: "h2", x: "Ownership of Rights" },
    { t: "clause", x: "The Platform, including all notes, mock tests, MCQs, recalls, and other study material, contains copyrighted material, trademarks, and other proprietary information owned by or licensed to AMC Catalyst. All intellectual property rights in the Platform and its content are owned by us." },
    { t: "clause", x: "Subject to your subscription, you are granted a limited, non-exclusive, non-transferable, revocable licence to access and view the content solely for your own personal, non-commercial exam-preparation use, in strict accordance with Section 7 (Content Protection) above. You may not modify, copy, distribute, re-post, transmit, display, print, download, screenshot, screen-record, publish, sell, license, create derivative works from, or otherwise exploit any content available on the Platform." },
    { t: "clause", x: "You acknowledge that you do not acquire any ownership rights in the content by virtue of your subscription. You shall be solely liable for any damage resulting from any infringement of our copyrights, trademarks, or other proprietary rights." },
    { t: "h2", x: "Your Rights in Relation to Personal Information Collected by Us" },
    { t: "p", x: "As a data principal, you have the following rights with respect to your Personal Information:" },
    { t: "clause", x: "Right to Access - You may request access to the Personal Information we hold about you." },
    { t: "clause", x: "Right to Correction - You may request us to correct any inaccuracies in your Personal Information." },
    { t: "clause", x: "Right to Erasure - You may request deletion of your Personal Information, subject to Applicable Law and our legitimate retention requirements described in Section 10." },
    { t: "clause", x: "Right to Withdraw Consent - Where processing is based on your consent, you may withdraw it at any time; however, this may affect your ability to access the Services." },
    { t: "clause", x: "Right to Restrict or Object to Processing - You may request restrictions on, or object to, the processing of your Personal Information." },
    { t: "clause", x: "Right to Nominate a Representative - You may nominate a person to act on your behalf in relation to your Personal Information in the event of your death or incapacity." },
    { t: "clause", x: "All requests under this Section will be acknowledged and responded to within 72 hours of receipt. To exercise any of these rights, please contact our Data Protection Officer using the details in Section 19." },
    { t: "h2", x: "Conditions of Use" },
    { t: "clause", x: "We do not warrant that the Platform, its servers, or emails sent by us are virus-free. We shall not be liable for any damages of any kind arising from the use of the Platform, including compensatory, direct, indirect, incidental, punitive, special, or consequential damages, including for loss of study progress, data, or income." },
    { t: "clause", x: "In order to provide and administer the Services, we may communicate with you through email, SMS, WhatsApp, push notifications, or other modes of communication permitted under Applicable Law, including OTPs, payment receipts, renewal reminders, security alerts, and other service-related notifications, which may continue notwithstanding your decision to opt out of promotional communications." },
    { t: "clause", x: "We may disclose your Personal Information where required or permitted under Applicable Law, to enforce our Terms of Use, protect our rights, investigate fraud, unauthorised account sharing, or content redistribution, or respond to lawful governmental requests." },
    { t: "h2", x: "Data Protection Officer" },
    { t: "p", x: "If you have any questions, concerns, or complaints regarding this Privacy Policy or the processing of your Personal Information, you may contact our Data Protection Officer:" },
    { t: "p", x: "Name: [to be provided]" },
    { t: "p", x: "Designation: Data Protection Officer" },
    { t: "p", x: "Email: [to be provided]" },
    { t: "p", x: "Grievance Email: [to be provided]" },
    { t: "p", x: "Customer Support: [to be provided]" },
    { t: "p", x: "We aim to acknowledge privacy-related requests within 48 hours and endeavour to resolve them within 15 business days, subject to the nature and complexity of the request." },
    { t: "h2", x: "Consent to the Policy" },
    { t: "clause", x: "We will only process your Personal Information where you have provided free, specific, informed, and unambiguous consent, in accordance with Applicable Law. Such consent will be sought separately for each purpose of processing and shall not be bundled with acceptance of any other terms." },
    { t: "clause", x: "Your consent will be taken at every stage where any new category of Personal Information is required or where the purpose of its use changes. We will share your Personal Information with third parties only where you have expressly permitted us to do so, except as otherwise set out in this Policy." },
    { t: "clause", x: "At any time, you may withdraw your consent through your account settings or by submitting a request to our Data Protection Officer; however, in the event consent is withdrawn, we may be unable to provide some or all portions of the Services that rely on such data, and this shall not entitle you to a refund." },
    { t: "clause", x: "Acceptance of our Terms of Use, including the One Account, One User policy, Content Protection restrictions, and No Refund Policy, is a separate and mandatory requirement for accessing and using the Platform. If you do not agree to the Terms of Use and/or do not provide the required consents, we may not be able to offer you access to the Services." },
    { t: "h2", x: "Governing Law and Jurisdiction" },
    { t: "p", x: "This Privacy Policy shall be governed by and construed in accordance with the laws of India. Subject to Applicable Law, the courts at Kochi, India shall have exclusive jurisdiction over any disputes arising out of or in connection with this Privacy Policy." },
  ],
};

